version: "3.8"

services:
  web:
    build: .
    container_name: chat-app-connected-notion
    command: tail -f /dev/null # temporary setting
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/dev_database

  db:
    image: postgres:13
    container_name: chat-app-connected-notion-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev_database
    ports:
      - "5432:5432"
    volumes:
      - chat_app_connected_notion_db_data:/var/lib/postgresql/data

volumes:
  chat_app_connected_notion_db_data:
